In [1]:
import numpy as np
x = np.array([[1, 3, 5], [11, 35, 56]]) 

In [2]:
x

array([[ 1,  3,  5],
       [11, 35, 56]])

In [3]:
y = np.ravel(x, order='F')  
z = np.ravel(x, order='C')  
p = np.ravel(x, order='A')  
q = np.ravel(x, order='K')  
y  
z  
p  
q  

array([ 1,  3,  5, 11, 35, 56])

In [4]:
y

array([ 1, 11,  3, 35,  5, 56])

In [5]:
z

array([ 1,  3,  5, 11, 35, 56])

In [6]:
p

array([ 1,  3,  5, 11, 35, 56])

In [7]:
q

array([ 1,  3,  5, 11, 35, 56])

In [10]:
x = np.arange(12).reshape(3,2,2).swapaxes(1,2)

In [12]:
x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

In [13]:
len(x)

2

In [14]:
x[0]

array([[0, 1],
       [2, 3]])

In [15]:
x.swapaxes(0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [16]:
x.shape

(2, 2, 2)

In [18]:
x=np.array([(1, 2), (3, 4)])

In [19]:
x

array([[1, 2],
       [3, 4]])

In [20]:
len(x)

2

In [21]:
x.shape

(2, 2)

In [26]:
a = np.array([[(1, 2), (3, 4)]])
np.shape(a)

a.shape


(1, 2, 2)

In [27]:
a

array([[[1, 2],
        [3, 4]]])